#define JOB_DISPLAY_ORDER_MAYOR 1
#define JOB_DISPLAY_ORDER_SECRETARY 2
#define JOB_DISPLAY_ORDER_SHERIFF 3
#define JOB_DISPLAY_ORDER_DEPUTY 4
#define JOB_DISPLAY_ORDER_DETECTIVE 5
#define JOB_DISPLAY_ORDER_FARMER 6
#define JOB_DISPLAY_ORDER_DOCTOR 7
#define JOB_DISPLAY_ORDER_NEWSANCHOR 8
#define JOB_DISPLAY_ORDER_CIVILIAN 9
#define EXP_TYPE_TOWN "Town"

