#define JOB_DISPLAY_ORDER_MAYOR 1
#define JOB_DISPLAY_ORDER_SHERIFF 2
#define JOB_DISPLAY_ORDER_FARMER 3
#define JOB_DISPLAY_ORDER_DOCTOR 4
#define JOB_DISPLAY_ORDER_CIVILIAN 5

#define EXP_TYPE_TOWN "Town"

